version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    branches:
      ignore:
        - gh-pages

    steps:
      # Checkout, with submodules
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum ".circleci/config.yml" }}
            - v1-dependencies-

      - run:
          name: Update SonarQube
          command: gradle sonarqube -Dsonar.projectKey=gladed_watchable -Dsonar.organization=gladed-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN

      - run:
          name: Build and test
          command: gradle detekt check

      - run:
          name: Update codecov.io
          command: bash <(curl -s https://codecov.io/bash)

      # Capture dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum ".circleci/config.yml" }}

      - store_test_results:
          path: ./build/test-results
